//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public long Id { get; set; }
        public Nullable<int> IdHealthCareProvider { get; set; }
        public Nullable<int> IdPhysician { get; set; }
        public Nullable<int> IdMedicalCase { get; set; }
        public string InsuranceCardNumber { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual HealthCareProvider HealthCareProvider { get; set; }
        public virtual InsurancePolicy InsurancePolicy { get; set; }
        public virtual Physician Physician { get; set; }
    }
}
