//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsurancePolicy()
        {
            this.Claims = new HashSet<Claim>();
        }
    
        public long Id { get; set; }
        public string InsuranceCardNumber { get; set; }
        public Nullable<long> IdBeneficiary { get; set; }
        public Nullable<int> IdPolicy { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual Beneficiary Beneficiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual PolicyInformation PolicyInformation { get; set; }
    }
}
