//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int Id { get; set; }
        public Nullable<long> IdBeneficiary { get; set; }
        public Nullable<int> IdMedicalCase { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    
        public virtual Beneficiary Beneficiary { get; set; }
        public virtual MedicalCase MedicalCase { get; set; }
    }
}
