//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalCase()
        {
            this.MedicalHistories = new HashSet<MedicalHistory>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Notes { get; set; }
    
        public virtual CaseCategory CaseCategory { get; set; }
        public virtual CaseType CaseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistory> MedicalHistories { get; set; }
    }
}
