//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyInformation()
        {
            this.InsurancePolicies = new HashSet<InsurancePolicy>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> MaxCoveredAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePolicy> InsurancePolicies { get; set; }
    }
}
